misc: slot_status: Fix error cause a function declaration is deprecated
../kernel/nothing/sm7325/drivers/misc/slot_status.c:54:25: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
static int slot_parse_dt()
                        ^
                         void
1 error generated.

Signed-off-by: BrainKub <fyhtjnt@gmail.com>